name: shellcheck

on:
  push:
    branches: [main, initial]
    paths: ['**.sh', '.shellcheckrc']
  pull_request:
    paths: ['**.sh', '.shellcheckrc']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run shellcheck
        run: make lint
